package easy.config.doc;

import javax.swing.*;

public class JavaDocConfig {

    private String author;
    private String dateFormat;
    private String methodReturnType;
    private String propertyCommentType;
    private String propertyCommentModel;
    private Boolean autoGenerateDocClass;
    private Boolean autoGenerateDocMethod;
    private Boolean autoGenerateDocField;
    private String coverModel;
    private Boolean coverHintPrompt;
    private Boolean classBatchEnable;
    private Boolean methodBatchEnable;
    private Boolean fieldBatchEnable;
    private Boolean innerClassBatchEnable;
    private Boolean getAndSetMethodBatchEnable;
    private Boolean constructorMethodBatchEnable;

    // 类、方法、属性的JavaDoc模板配置持久化
    private JavaDocTemplateConfig javaDocClassTemplateConfig = new JavaDocTemplateConfig();
    private JavaDocTemplateConfig javaDocMethodTemplateConfig = new JavaDocTemplateConfig();
    private JavaDocTemplateConfig javaDocFieldTemplateConfig = new JavaDocTemplateConfig();

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    public String getMethodReturnType() {
        return methodReturnType;
    }

    public void setMethodReturnType(String methodReturnType) {
        this.methodReturnType = methodReturnType;
    }

    public String getPropertyCommentType() {
        return propertyCommentType;
    }

    public void setPropertyCommentType(String propertyCommentType) {
        this.propertyCommentType = propertyCommentType;
    }

    public String getPropertyCommentModel() {
        return propertyCommentModel;
    }

    public void setPropertyCommentModel(String propertyCommentModel) {
        this.propertyCommentModel = propertyCommentModel;
    }

    public Boolean getAutoGenerateDocClass() {
        return autoGenerateDocClass;
    }

    public void setAutoGenerateDocClass(Boolean autoGenerateDocClass) {
        this.autoGenerateDocClass = autoGenerateDocClass;
    }

    public Boolean getAutoGenerateDocMethod() {
        return autoGenerateDocMethod;
    }

    public void setAutoGenerateDocMethod(Boolean autoGenerateDocMethod) {
        this.autoGenerateDocMethod = autoGenerateDocMethod;
    }

    public Boolean getAutoGenerateDocField() {
        return autoGenerateDocField;
    }

    public void setAutoGenerateDocField(Boolean autoGenerateDocField) {
        this.autoGenerateDocField = autoGenerateDocField;
    }

    public String getCoverModel() {
        return coverModel;
    }

    public void setCoverModel(String coverModel) {
        this.coverModel = coverModel;
    }

    public JavaDocTemplateConfig getJavaDocClassTemplateConfig() {
        if (javaDocClassTemplateConfig == null) {
            javaDocClassTemplateConfig = new JavaDocTemplateConfig();
        }
        return javaDocClassTemplateConfig;
    }

    public void setJavaDocClassTemplateConfig(JavaDocTemplateConfig javaDocClassTemplateConfig) {
        this.javaDocClassTemplateConfig = javaDocClassTemplateConfig;
    }

    public JavaDocTemplateConfig getJavaDocMethodTemplateConfig() {
        if (javaDocMethodTemplateConfig == null) {
            javaDocMethodTemplateConfig = new JavaDocTemplateConfig();
        }
        return javaDocMethodTemplateConfig;
    }

    public void setJavaDocMethodTemplateConfig(JavaDocTemplateConfig javaDocMethodTemplateConfig) {
        this.javaDocMethodTemplateConfig = javaDocMethodTemplateConfig;
    }

    public JavaDocTemplateConfig getJavaDocFieldTemplateConfig() {
        if (javaDocFieldTemplateConfig == null) {
            javaDocFieldTemplateConfig = new JavaDocTemplateConfig();
        }
        return javaDocFieldTemplateConfig;
    }

    public void setJavaDocFieldTemplateConfig(JavaDocTemplateConfig javaDocFieldTemplateConfig) {
        this.javaDocFieldTemplateConfig = javaDocFieldTemplateConfig;
    }

    public Boolean getCoverHintPrompt() {
        return coverHintPrompt;
    }

    public void setCoverHintPrompt(Boolean coverHintPrompt) {
        this.coverHintPrompt = coverHintPrompt;
    }

    public Boolean getClassBatchEnable() {
        return classBatchEnable;
    }

    public void setClassBatchEnable(Boolean classBatchEnable) {
        this.classBatchEnable = classBatchEnable;
    }

    public Boolean getMethodBatchEnable() {
        return methodBatchEnable;
    }

    public void setMethodBatchEnable(Boolean methodBatchEnable) {
        this.methodBatchEnable = methodBatchEnable;
    }

    public Boolean getFieldBatchEnable() {
        return fieldBatchEnable;
    }

    public void setFieldBatchEnable(Boolean fieldBatchEnable) {
        this.fieldBatchEnable = fieldBatchEnable;
    }

    public Boolean getInnerClassBatchEnable() {
        return innerClassBatchEnable;
    }

    public void setInnerClassBatchEnable(Boolean innerClassBatchEnable) {
        this.innerClassBatchEnable = innerClassBatchEnable;
    }

    public Boolean getGetAndSetMethodBatchEnable() {
        return getAndSetMethodBatchEnable;
    }

    public void setGetAndSetMethodBatchEnable(Boolean getAndSetMethodBatchEnable) {
        this.getAndSetMethodBatchEnable = getAndSetMethodBatchEnable;
    }

    public Boolean getConstructorMethodBatchEnable() {
        return constructorMethodBatchEnable;
    }

    public void setConstructorMethodBatchEnable(Boolean constructorMethodBatchEnable) {
        this.constructorMethodBatchEnable = constructorMethodBatchEnable;
    }
}
